{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": []
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "code",
      "source": [
        "#Gépi tanulás TOP ML-ek\n",
        "from sklearn.datasets import load_iris\n",
        "from sklearn.model_selection import train_test_split\n",
        "from sklearn.metrics import accuracy_score\n",
        "\n",
        "# Adat betöltése\n",
        "data = load_iris()\n",
        "X = data.data\n",
        "y = data.target\n",
        "\n",
        "# Tanító és teszt halmaz\n",
        "X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)\n",
        "#--------------------------------\n",
        "import pandas as pd\n",
        "\n",
        "try:\n",
        "    df = pd.read_csv('Top-50-musicality-global.csv')\n",
        "    print(\"Data loaded successfully from 'your_data.csv':\")\n",
        "    display(df.head())\n",
        "except FileNotFoundError:\n",
        "    print(\"Error: 'your_data.csv' not found. Please make sure the file is in the correct directory or provide the full path.\")\n",
        "except Exception as e:\n",
        "    print(f\"An error occurred while loading the CSV: {e}\")\n",
        "\n",
        "#---------------------------------\n",
        "\n",
        "# Naiv Bayes\n",
        "\n",
        "from sklearn.naive_bayes import GaussianNB\n",
        "\n",
        "model = GaussianNB()\n",
        "model.fit(X_train, y_train)\n",
        "\n",
        "pred = model.predict(X_test)\n",
        "print(\"Naive Bayes pontosság:\", accuracy_score(y_test, pred))\n",
        "\n",
        "# Logisztikus regresszió\n",
        "\n",
        "from sklearn.linear_model import LogisticRegression\n",
        "\n",
        "model = LogisticRegression(max_iter=1000)\n",
        "model.fit(X_train, y_train)\n",
        "\n",
        "pred = model.predict(X_test)\n",
        "print(\"Logisztikus regresszió pontosság:\", accuracy_score(y_test, pred))\n",
        "\n",
        "# Döntés fa\n",
        "\n",
        "from sklearn.tree import DecisionTreeClassifier\n",
        "\n",
        "model = DecisionTreeClassifier()\n",
        "model.fit(X_train, y_train)\n",
        "\n",
        "pred = model.predict(X_test)\n",
        "print(\"Döntési fa pontosság:\", accuracy_score(y_test, pred))\n",
        "\n",
        "# KNN legközelebbi szomszéd\n",
        "\n",
        "from sklearn.neighbors import KNeighborsClassifier\n",
        "\n",
        "model = KNeighborsClassifier(n_neighbors=5)\n",
        "model.fit(X_train, y_train)\n",
        "\n",
        "pred = model.predict(X_test)\n",
        "print(\"KNN pontosság:\", accuracy_score(y_test, pred))\n",
        "\n",
        "# Random forrest\n",
        "\n",
        "from sklearn.ensemble import RandomForestClassifier\n",
        "\n",
        "model = RandomForestClassifier(n_estimators=100)\n",
        "model.fit(X_train, y_train)\n",
        "\n",
        "pred = model.predict(X_test)\n",
        "print(\"Random Forest pontosság:\", accuracy_score(y_test, pred))\n",
        "\n",
        "# Support vector machine\n",
        "\n",
        "from sklearn.svm import SVC\n",
        "\n",
        "model = SVC()\n",
        "model.fit(X_train, y_train)\n",
        "\n",
        "pred = model.predict(X_test)\n",
        "print(\"SVC pontosság:\", accuracy_score(y_test, pred))\n",
        "\n",
        "# XG boost\n",
        "\n",
        "from xgboost import XGBClassifier\n",
        "\n",
        "model = XGBClassifier(use_label_encoder=False, eval_metric='mlogloss')\n",
        "model.fit(X_train, y_train)\n",
        "\n",
        "pred = model.predict(X_test)\n",
        "print(\"XGBoost pontosság:\", accuracy_score(y_test, pred))\n",
        "\n",
        "# Soft voting classifier\n",
        "\n",
        "from sklearn.ensemble import VotingClassifier\n",
        "from sklearn.linear_model import LogisticRegression\n",
        "from sklearn.svm import SVC\n",
        "from sklearn.tree import DecisionTreeClassifier\n",
        "\n",
        "model = VotingClassifier(\n",
        "estimators=[\n",
        "('lr', LogisticRegression(max_iter=1000)),\n",
        "('svc', SVC(probability=True)),\n",
        "('dt', DecisionTreeClassifier())\n",
        "],\n",
        "voting='soft' # valószínűségekkel szavaz\n",
        ")\n",
        "\n",
        "model.fit(X_train, y_train)\n",
        "\n",
        "pred = model.predict(X_test)\n",
        "print(\"Soft Voting pontosság:\", accuracy_score(y_test, pred))\n",
        "\n"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 742
        },
        "id": "w_2LnownEKoo",
        "outputId": "6f49ffc9-710b-4fdd-979d-938965e5382f"
      },
      "execution_count": 3,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Data loaded successfully from 'your_data.csv':\n"
          ]
        },
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "   Unnamed: 0 Country                                         Track Name  \\\n",
              "0           0  Global                               Standing Next to You   \n",
              "1           1  Global                                             greedy   \n",
              "2           2  Global                                        Si No Estás   \n",
              "3           3  Global                Seven (feat. Latto) (Explicit Ver.)   \n",
              "4           4  Global  Is It Over Now? (Taylor's Version) (From The V...   \n",
              "\n",
              "      Artist Name               Album Name  Popularity        Date Markets  \\\n",
              "0       Jung Kook                   GOLDEN          91  2023-11-03      AR   \n",
              "1      Tate McRae                   greedy         100  2023-09-15      AR   \n",
              "2  iñigo quintero              Si No Estás          99  2022-09-23      AR   \n",
              "3       Jung Kook                   GOLDEN          82  2023-11-03      AR   \n",
              "4    Taylor Swift  1989 (Taylor's Version)          93  2023-10-26      AR   \n",
              "\n",
              "   Danceability  Acousticness  ...  Energy  Instrumentalness  Key  Liveness  \\\n",
              "0         0.711        0.0447  ...   0.809               0.0    2    0.3390   \n",
              "1         0.750        0.2560  ...   0.733               0.0    6    0.1140   \n",
              "2         0.537        0.8270  ...   0.421               0.0    5    0.1380   \n",
              "3         0.790        0.3120  ...   0.831               0.0   11    0.0797   \n",
              "4         0.596        0.0504  ...   0.658               0.0    0    0.1270   \n",
              "\n",
              "   Loudness  Mode  Speechiness    Tempo  TSignature  Positiveness  \n",
              "0    -4.389     0       0.0955  106.017           4         0.816  \n",
              "1    -3.180     0       0.0319  111.018           1         0.844  \n",
              "2    -8.720     1       0.0285   98.224           4         0.524  \n",
              "3    -4.185     1       0.0440  124.987           4         0.872  \n",
              "4    -7.346     1       0.0360  100.012           4         0.176  \n",
              "\n",
              "[5 rows x 21 columns]"
            ],
            "text/html": [
              "\n",
              "  <div id=\"df-b7076597-fcb2-4b54-8b6d-563e22f9c456\" class=\"colab-df-container\">\n",
              "    <div>\n",
              "<style scoped>\n",
              "    .dataframe tbody tr th:only-of-type {\n",
              "        vertical-align: middle;\n",
              "    }\n",
              "\n",
              "    .dataframe tbody tr th {\n",
              "        vertical-align: top;\n",
              "    }\n",
              "\n",
              "    .dataframe thead th {\n",
              "        text-align: right;\n",
              "    }\n",
              "</style>\n",
              "<table border=\"1\" class=\"dataframe\">\n",
              "  <thead>\n",
              "    <tr style=\"text-align: right;\">\n",
              "      <th></th>\n",
              "      <th>Unnamed: 0</th>\n",
              "      <th>Country</th>\n",
              "      <th>Track Name</th>\n",
              "      <th>Artist Name</th>\n",
              "      <th>Album Name</th>\n",
              "      <th>Popularity</th>\n",
              "      <th>Date</th>\n",
              "      <th>Markets</th>\n",
              "      <th>Danceability</th>\n",
              "      <th>Acousticness</th>\n",
              "      <th>...</th>\n",
              "      <th>Energy</th>\n",
              "      <th>Instrumentalness</th>\n",
              "      <th>Key</th>\n",
              "      <th>Liveness</th>\n",
              "      <th>Loudness</th>\n",
              "      <th>Mode</th>\n",
              "      <th>Speechiness</th>\n",
              "      <th>Tempo</th>\n",
              "      <th>TSignature</th>\n",
              "      <th>Positiveness</th>\n",
              "    </tr>\n",
              "  </thead>\n",
              "  <tbody>\n",
              "    <tr>\n",
              "      <th>0</th>\n",
              "      <td>0</td>\n",
              "      <td>Global</td>\n",
              "      <td>Standing Next to You</td>\n",
              "      <td>Jung Kook</td>\n",
              "      <td>GOLDEN</td>\n",
              "      <td>91</td>\n",
              "      <td>2023-11-03</td>\n",
              "      <td>AR</td>\n",
              "      <td>0.711</td>\n",
              "      <td>0.0447</td>\n",
              "      <td>...</td>\n",
              "      <td>0.809</td>\n",
              "      <td>0.0</td>\n",
              "      <td>2</td>\n",
              "      <td>0.3390</td>\n",
              "      <td>-4.389</td>\n",
              "      <td>0</td>\n",
              "      <td>0.0955</td>\n",
              "      <td>106.017</td>\n",
              "      <td>4</td>\n",
              "      <td>0.816</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>1</th>\n",
              "      <td>1</td>\n",
              "      <td>Global</td>\n",
              "      <td>greedy</td>\n",
              "      <td>Tate McRae</td>\n",
              "      <td>greedy</td>\n",
              "      <td>100</td>\n",
              "      <td>2023-09-15</td>\n",
              "      <td>AR</td>\n",
              "      <td>0.750</td>\n",
              "      <td>0.2560</td>\n",
              "      <td>...</td>\n",
              "      <td>0.733</td>\n",
              "      <td>0.0</td>\n",
              "      <td>6</td>\n",
              "      <td>0.1140</td>\n",
              "      <td>-3.180</td>\n",
              "      <td>0</td>\n",
              "      <td>0.0319</td>\n",
              "      <td>111.018</td>\n",
              "      <td>1</td>\n",
              "      <td>0.844</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>2</th>\n",
              "      <td>2</td>\n",
              "      <td>Global</td>\n",
              "      <td>Si No Estás</td>\n",
              "      <td>iñigo quintero</td>\n",
              "      <td>Si No Estás</td>\n",
              "      <td>99</td>\n",
              "      <td>2022-09-23</td>\n",
              "      <td>AR</td>\n",
              "      <td>0.537</td>\n",
              "      <td>0.8270</td>\n",
              "      <td>...</td>\n",
              "      <td>0.421</td>\n",
              "      <td>0.0</td>\n",
              "      <td>5</td>\n",
              "      <td>0.1380</td>\n",
              "      <td>-8.720</td>\n",
              "      <td>1</td>\n",
              "      <td>0.0285</td>\n",
              "      <td>98.224</td>\n",
              "      <td>4</td>\n",
              "      <td>0.524</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>3</th>\n",
              "      <td>3</td>\n",
              "      <td>Global</td>\n",
              "      <td>Seven (feat. Latto) (Explicit Ver.)</td>\n",
              "      <td>Jung Kook</td>\n",
              "      <td>GOLDEN</td>\n",
              "      <td>82</td>\n",
              "      <td>2023-11-03</td>\n",
              "      <td>AR</td>\n",
              "      <td>0.790</td>\n",
              "      <td>0.3120</td>\n",
              "      <td>...</td>\n",
              "      <td>0.831</td>\n",
              "      <td>0.0</td>\n",
              "      <td>11</td>\n",
              "      <td>0.0797</td>\n",
              "      <td>-4.185</td>\n",
              "      <td>1</td>\n",
              "      <td>0.0440</td>\n",
              "      <td>124.987</td>\n",
              "      <td>4</td>\n",
              "      <td>0.872</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>4</th>\n",
              "      <td>4</td>\n",
              "      <td>Global</td>\n",
              "      <td>Is It Over Now? (Taylor's Version) (From The V...</td>\n",
              "      <td>Taylor Swift</td>\n",
              "      <td>1989 (Taylor's Version)</td>\n",
              "      <td>93</td>\n",
              "      <td>2023-10-26</td>\n",
              "      <td>AR</td>\n",
              "      <td>0.596</td>\n",
              "      <td>0.0504</td>\n",
              "      <td>...</td>\n",
              "      <td>0.658</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0</td>\n",
              "      <td>0.1270</td>\n",
              "      <td>-7.346</td>\n",
              "      <td>1</td>\n",
              "      <td>0.0360</td>\n",
              "      <td>100.012</td>\n",
              "      <td>4</td>\n",
              "      <td>0.176</td>\n",
              "    </tr>\n",
              "  </tbody>\n",
              "</table>\n",
              "<p>5 rows × 21 columns</p>\n",
              "</div>\n",
              "    <div class=\"colab-df-buttons\">\n",
              "\n",
              "  <div class=\"colab-df-container\">\n",
              "    <button class=\"colab-df-convert\" onclick=\"convertToInteractive('df-b7076597-fcb2-4b54-8b6d-563e22f9c456')\"\n",
              "            title=\"Convert this dataframe to an interactive table.\"\n",
              "            style=\"display:none;\">\n",
              "\n",
              "  <svg xmlns=\"http://www.w3.org/2000/svg\" height=\"24px\" viewBox=\"0 -960 960 960\">\n",
              "    <path d=\"M120-120v-720h720v720H120Zm60-500h600v-160H180v160Zm220 220h160v-160H400v160Zm0 220h160v-160H400v160ZM180-400h160v-160H180v160Zm440 0h160v-160H620v160ZM180-180h160v-160H180v160Zm440 0h160v-160H620v160Z\"/>\n",
              "  </svg>\n",
              "    </button>\n",
              "\n",
              "  <style>\n",
              "    .colab-df-container {\n",
              "      display:flex;\n",
              "      gap: 12px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert {\n",
              "      background-color: #E8F0FE;\n",
              "      border: none;\n",
              "      border-radius: 50%;\n",
              "      cursor: pointer;\n",
              "      display: none;\n",
              "      fill: #1967D2;\n",
              "      height: 32px;\n",
              "      padding: 0 0 0 0;\n",
              "      width: 32px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert:hover {\n",
              "      background-color: #E2EBFA;\n",
              "      box-shadow: 0px 1px 2px rgba(60, 64, 67, 0.3), 0px 1px 3px 1px rgba(60, 64, 67, 0.15);\n",
              "      fill: #174EA6;\n",
              "    }\n",
              "\n",
              "    .colab-df-buttons div {\n",
              "      margin-bottom: 4px;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert {\n",
              "      background-color: #3B4455;\n",
              "      fill: #D2E3FC;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert:hover {\n",
              "      background-color: #434B5C;\n",
              "      box-shadow: 0px 1px 3px 1px rgba(0, 0, 0, 0.15);\n",
              "      filter: drop-shadow(0px 1px 2px rgba(0, 0, 0, 0.3));\n",
              "      fill: #FFFFFF;\n",
              "    }\n",
              "  </style>\n",
              "\n",
              "    <script>\n",
              "      const buttonEl =\n",
              "        document.querySelector('#df-b7076597-fcb2-4b54-8b6d-563e22f9c456 button.colab-df-convert');\n",
              "      buttonEl.style.display =\n",
              "        google.colab.kernel.accessAllowed ? 'block' : 'none';\n",
              "\n",
              "      async function convertToInteractive(key) {\n",
              "        const element = document.querySelector('#df-b7076597-fcb2-4b54-8b6d-563e22f9c456');\n",
              "        const dataTable =\n",
              "          await google.colab.kernel.invokeFunction('convertToInteractive',\n",
              "                                                    [key], {});\n",
              "        if (!dataTable) return;\n",
              "\n",
              "        const docLinkHtml = 'Like what you see? Visit the ' +\n",
              "          '<a target=\"_blank\" href=https://colab.research.google.com/notebooks/data_table.ipynb>data table notebook</a>'\n",
              "          + ' to learn more about interactive tables.';\n",
              "        element.innerHTML = '';\n",
              "        dataTable['output_type'] = 'display_data';\n",
              "        await google.colab.output.renderOutput(dataTable, element);\n",
              "        const docLink = document.createElement('div');\n",
              "        docLink.innerHTML = docLinkHtml;\n",
              "        element.appendChild(docLink);\n",
              "      }\n",
              "    </script>\n",
              "  </div>\n",
              "\n",
              "\n",
              "    <div id=\"df-f29b0c4a-d63b-496b-b1ed-ba58fe1e0eaf\">\n",
              "      <button class=\"colab-df-quickchart\" onclick=\"quickchart('df-f29b0c4a-d63b-496b-b1ed-ba58fe1e0eaf')\"\n",
              "                title=\"Suggest charts\"\n",
              "                style=\"display:none;\">\n",
              "\n",
              "<svg xmlns=\"http://www.w3.org/2000/svg\" height=\"24px\"viewBox=\"0 0 24 24\"\n",
              "     width=\"24px\">\n",
              "    <g>\n",
              "        <path d=\"M19 3H5c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zM9 17H7v-7h2v7zm4 0h-2V7h2v10zm4 0h-2v-4h2v4z\"/>\n",
              "    </g>\n",
              "</svg>\n",
              "      </button>\n",
              "\n",
              "<style>\n",
              "  .colab-df-quickchart {\n",
              "      --bg-color: #E8F0FE;\n",
              "      --fill-color: #1967D2;\n",
              "      --hover-bg-color: #E2EBFA;\n",
              "      --hover-fill-color: #174EA6;\n",
              "      --disabled-fill-color: #AAA;\n",
              "      --disabled-bg-color: #DDD;\n",
              "  }\n",
              "\n",
              "  [theme=dark] .colab-df-quickchart {\n",
              "      --bg-color: #3B4455;\n",
              "      --fill-color: #D2E3FC;\n",
              "      --hover-bg-color: #434B5C;\n",
              "      --hover-fill-color: #FFFFFF;\n",
              "      --disabled-bg-color: #3B4455;\n",
              "      --disabled-fill-color: #666;\n",
              "  }\n",
              "\n",
              "  .colab-df-quickchart {\n",
              "    background-color: var(--bg-color);\n",
              "    border: none;\n",
              "    border-radius: 50%;\n",
              "    cursor: pointer;\n",
              "    display: none;\n",
              "    fill: var(--fill-color);\n",
              "    height: 32px;\n",
              "    padding: 0;\n",
              "    width: 32px;\n",
              "  }\n",
              "\n",
              "  .colab-df-quickchart:hover {\n",
              "    background-color: var(--hover-bg-color);\n",
              "    box-shadow: 0 1px 2px rgba(60, 64, 67, 0.3), 0 1px 3px 1px rgba(60, 64, 67, 0.15);\n",
              "    fill: var(--button-hover-fill-color);\n",
              "  }\n",
              "\n",
              "  .colab-df-quickchart-complete:disabled,\n",
              "  .colab-df-quickchart-complete:disabled:hover {\n",
              "    background-color: var(--disabled-bg-color);\n",
              "    fill: var(--disabled-fill-color);\n",
              "    box-shadow: none;\n",
              "  }\n",
              "\n",
              "  .colab-df-spinner {\n",
              "    border: 2px solid var(--fill-color);\n",
              "    border-color: transparent;\n",
              "    border-bottom-color: var(--fill-color);\n",
              "    animation:\n",
              "      spin 1s steps(1) infinite;\n",
              "  }\n",
              "\n",
              "  @keyframes spin {\n",
              "    0% {\n",
              "      border-color: transparent;\n",
              "      border-bottom-color: var(--fill-color);\n",
              "      border-left-color: var(--fill-color);\n",
              "    }\n",
              "    20% {\n",
              "      border-color: transparent;\n",
              "      border-left-color: var(--fill-color);\n",
              "      border-top-color: var(--fill-color);\n",
              "    }\n",
              "    30% {\n",
              "      border-color: transparent;\n",
              "      border-left-color: var(--fill-color);\n",
              "      border-top-color: var(--fill-color);\n",
              "      border-right-color: var(--fill-color);\n",
              "    }\n",
              "    40% {\n",
              "      border-color: transparent;\n",
              "      border-right-color: var(--fill-color);\n",
              "      border-top-color: var(--fill-color);\n",
              "    }\n",
              "    60% {\n",
              "      border-color: transparent;\n",
              "      border-right-color: var(--fill-color);\n",
              "    }\n",
              "    80% {\n",
              "      border-color: transparent;\n",
              "      border-right-color: var(--fill-color);\n",
              "      border-bottom-color: var(--fill-color);\n",
              "    }\n",
              "    90% {\n",
              "      border-color: transparent;\n",
              "      border-bottom-color: var(--fill-color);\n",
              "    }\n",
              "  }\n",
              "</style>\n",
              "\n",
              "      <script>\n",
              "        async function quickchart(key) {\n",
              "          const quickchartButtonEl =\n",
              "            document.querySelector('#' + key + ' button');\n",
              "          quickchartButtonEl.disabled = true;  // To prevent multiple clicks.\n",
              "          quickchartButtonEl.classList.add('colab-df-spinner');\n",
              "          try {\n",
              "            const charts = await google.colab.kernel.invokeFunction(\n",
              "                'suggestCharts', [key], {});\n",
              "          } catch (error) {\n",
              "            console.error('Error during call to suggestCharts:', error);\n",
              "          }\n",
              "          quickchartButtonEl.classList.remove('colab-df-spinner');\n",
              "          quickchartButtonEl.classList.add('colab-df-quickchart-complete');\n",
              "        }\n",
              "        (() => {\n",
              "          let quickchartButtonEl =\n",
              "            document.querySelector('#df-f29b0c4a-d63b-496b-b1ed-ba58fe1e0eaf button');\n",
              "          quickchartButtonEl.style.display =\n",
              "            google.colab.kernel.accessAllowed ? 'block' : 'none';\n",
              "        })();\n",
              "      </script>\n",
              "    </div>\n",
              "\n",
              "    </div>\n",
              "  </div>\n"
            ],
            "application/vnd.google.colaboratory.intrinsic+json": {
              "type": "dataframe"
            }
          },
          "metadata": {}
        },
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Naive Bayes pontosság: 0.9666666666666667\n",
            "Logisztikus regresszió pontosság: 1.0\n",
            "Döntési fa pontosság: 1.0\n",
            "KNN pontosság: 0.9666666666666667\n",
            "Random Forest pontosság: 1.0\n",
            "SVC pontosság: 1.0\n",
            "XGBoost pontosság: 1.0\n"
          ]
        },
        {
          "output_type": "stream",
          "name": "stderr",
          "text": [
            "/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [13:03:06] WARNING: /workspace/src/learner.cc:790: \n",
            "Parameters: { \"use_label_encoder\" } are not used.\n",
            "\n",
            "  bst.update(dtrain, iteration=i, fobj=obj)\n"
          ]
        },
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Soft Voting pontosság: 1.0\n"
          ]
        }
      ]
    }
  ]
}